Feature/update gcp docker documentation
idrsolutions/idrsolutions.github.io pull request #1
Opened 2020-10-05 12:56 UTC by daniel-warren

Update the GCP tutorial with new steps following the change to the docker images.

2020-10-07 15:59 UTC, leonatherton requested changes

2020-10-07 15:59 UTC, leonatherton commented on _includes/cloud-docker/googlecloud.md
> +4. Click submit
```suggestion
3. Submit your username and password
```
Rule of three

2020-10-07 15:59 UTC, leonatherton commented on _includes/cloud-docker/googlecloud.md
> +Enter 'idrsolutions/{{ page.product | downcase }}'
```suggestion
Enter `idrsolutions/{{ page.product | downcase }}` 
```
Makes it a snippet

2020-10-07 15:59 UTC, leonatherton commented on _includes/cloud-docker/googlecloud.md
> +This tutorial will run how to do this via SSH, for other methods click [here](https://cloud.google.com/compute/docs/instances/transfer-files).
```suggestion
This tutorial demonstrates how to do this via SSH, though [other methods](https://cloud.google.com/compute/docs/instances/transfer-files) are available.
```

2020-10-07 15:59 UTC, leonatherton commented on _includes/cloud-docker/googlecloud.md
> +Select  from your local file, and click 'Okay'.
```suggestion
Select the war file, and click 'Okay'.
```

2020-10-07 15:59 UTC, leonatherton commented on _includes/cloud-docker/googlecloud.md
> +By default, this will upload to the /home/$USER directory, where the volume mount was set to
```suggestion
By default, this will upload to the /home/$USER directory, where the volume mount is set to.
```

2020-10-07 15:59 UTC, leonatherton commented on _includes/cloud-docker/googlecloud.md
> +Otherwise, restart the VM after making these changes to ensure that the service starts correctly. Wait a few minutes again for the container to start up.
```suggestion
Otherwise, restart the VM after making these changes to ensure that the service starts correctly. Wait a few minutes again for the container to start up and move to [Running {{ page.product }}](#running-{{ page.product  || downcase }}).
```

2020-10-07 16:15 UTC, daniel-warren commented
@leonatherton - The suggested changes looked good, I have committed them.

2020-10-07 16:15 UTC, leonatherton approved these changes

2020-10-09 08:02 UTC, KieranFrance commented
Looks good to me

2020-10-09 08:02 UTC, KieranFrance approved these changes

2020-10-09 08:13 UTC, merged