Feature/update OCI docker documentation
idrsolutions/idrsolutions.github.io pull request #3
Opened 2020-10-06 15:06 UTC by daniel-warren

Update the OCI tutorial with new steps following the change to the docker images.

New PR where GCP changes are not accidentally included.

2020-10-07 10:26 UTC, Amy1612 commented on _includes/cloud-docker/oraclecloud.md
> +sudo docker run -p 80:80 --mount "source=/home/opc/{{ page.product | downcase }}_microservice.war,target=/usr/local/tomcat/webapps/ROOT.war,type=bind" idrsolutions/{{ page.product | downcase }}
Just checking here, not too sure but does it have to be tomcat in the target path or can it be like jetty, glassfish, etc. If so would it be worth noting this to the customer, like mount to the web app you set up.

2020-10-07 10:41 UTC, daniel-warren commented on _includes/cloud-docker/oraclecloud.md
> +sudo docker run -p 80:80 --mount "source=/home/opc/{{ page.product | downcase }}_microservice.war,target=/usr/local/tomcat/webapps/ROOT.war,type=bind" idrsolutions/{{ page.product | downcase }}
A good question! As this guide is specifically for using our provided docker images ([JPedal ](https://github.com/idrsolutions/jpedal-docker/blob/master/Dockerfile)/ [BuildVu](https://github.com/idrsolutions/buildvu-docker)) we can expect a set environment. If you check the Dockerfile in either project you'll see that the image is based on a Tomcat docker image, as such we only expect tomcat for the target path (at present the other app servers are not installed in the docker image).

2020-10-07 10:43 UTC, Amy1612 commented on _includes/cloud-docker/oraclecloud.md
> +sudo docker run -p 80:80 --mount "source=/home/opc/{{ page.product | downcase }}_microservice.war,target=/usr/local/tomcat/webapps/ROOT.war,type=bind" idrsolutions/{{ page.product | downcase }}
ahh okay, thank you for explaining!

2020-10-07 16:14 UTC, leonatherton requested changes

2020-10-07 16:14 UTC, leonatherton commented on _includes/cloud-docker/oraclecloud.md
> +4. Click submit.
```suggestion
3. Submit your username and password.
```

2020-10-07 16:14 UTC, leonatherton commented on _includes/cloud-docker/oraclecloud.md
> +These are used to set a username and password for your users to login with:
```suggestion
These are used to set a username and password to access the microservice:
```

2020-10-07 16:18 UTC, daniel-warren commented
@leonatherton - Suggested changes have been committed. Thanks for spotting.

2020-10-07 16:19 UTC, leonatherton approved these changes

2020-10-08 14:27 UTC, Amy1612 approved these changes

2020-10-12 08:46 UTC, KieranFrance approved these changes
Approved, as this is the last review please feel free to merge PR with develop branch

2020-10-12 09:15 UTC, merged