Feature/update digital ocean documentation
idrsolutions/idrsolutions.github.io pull request #5
Opened 2020-10-16 08:27 UTC by Amy1612

2020-10-19 10:54 UTC, daniel-warren requested changes
I've requested a few minor changes, though what has been added looks promising. 

One additional thing I thought I'd raise, (though it's not really blocking). Is it worth editing the FileZilla screenshots to not show the file names of the local environment? (With blurring or blanking them out). 
Doing so would mean less info is given about your development environment & there's less irrelevant information in the screenshots.

2020-10-19 10:54 UTC, daniel-warren commented on _includes/cloud-docker/digitalocean.md
> +docker run -p 80:80 -p 443:443 --mount "source=/opt/ssl,target=/opt/ssl,type=bind,readonly" idrsolutions/{{ page.product | downcase }}
In order for this command to work on the new solution, it would still need the war file mount in the command. 
```suggestion
docker run -p 80:80 -p 443:443 --mount "source=/path/to/war/{{ page.product | downcase }}-microservice.war,target=/usr/local/tomcat/webapps/ROOT.war,type=bind" --mount "source=/opt/ssl,target=/opt/ssl,type=bind,readonly" idrsolutions/{{ page.product | downcase }}
```

2020-10-19 10:54 UTC, daniel-warren commented on _includes/cloud-docker/digitalocean.md
> +docker run -d -p 80:80 -p 443:443 --mount "source=/opt/ssl,target=/opt/ssl,type=bind,readonly" idrsolutions/{{ page.product | downcase }}
In order for this command to work on the new solution, it would still need the war file mount in the command.
```suggestion
docker run -d -p 80:80 -p 443:443 --mount "source=/path/to/war/{{ page.product | downcase }}-microservice.war,target=/usr/local/tomcat/webapps/ROOT.war,type=bind" --mount "source=/opt/ssl,target=/opt/ssl,type=bind,readonly" idrsolutions/{{ page.product | downcase }}
```

2020-10-19 10:54 UTC, daniel-warren commented on _includes/cloud-docker/digitalocean.md
> +click on its IP address to copy it. If you wish to use HTTPS, you will need to create a DNS A record to map this IP address to a domain name.
Is there a reason "When it's done, " was removed?
If for conciseness I suggest that "Click" is capitalised. 
```suggestion
Click on its IP address to copy it. If you wish to use HTTPS, you will need to create a DNS A record to map this IP address to a domain name. 
```

2020-10-19 10:54 UTC, daniel-warren commented on _includes/cloud-docker/digitalocean.md
> +![12](/assets/images/digitalocean/12.png)
This screenshot currently lists jpedal-microservice.war. As effort has been made with other screenshots to use ProductName as a placeholder, is it worth updating this?

2020-10-19 10:58 UTC, daniel-warren commented on _includes/cloud-docker/digitalocean.md
> +docker run -p 80:80 --env ACCESS_USERNAME=<username> --env ACCESS_PASSWORD=<password> --mount "source=/path/to/war/{{ page.product | downcase }}-microservice.war,target=/usr/local/tomcat/webapps/ROOT
@Amy1612 - Something I missed with my review, as the upload guide notes adding the war file to the /root/ directory, should we alter /path/to/war/ to just /root/ ? (I have updated the two comments in the review which would be affected by this).
```suggestion
docker run -p 80:80 --env ACCESS_USERNAME=<username> --env ACCESS_PASSWORD=<password> --mount "source=/root/{{ page.product | downcase }}-microservice.war,target=/usr/local/tomcat/webapps/ROOT.war,type=bind" idrsolutions/{{ page.product | downcase }}
```

2020-10-19 13:21 UTC, daniel-warren approved these changes

2020-10-19 14:54 UTC, KieranFrance approved these changes

2020-10-20 14:13 UTC, leonatherton requested changes

2020-10-20 14:13 UTC, leonatherton commented on _includes/cloud-docker/digitalocean.md
> +if you set ACCESS_USERNAME and ACCESS_PASSWORD environment variables they will be required in order to connect to the {{ page.product }} droplet.
```suggestion
If you set ACCESS_USERNAME and ACCESS_PASSWORD environment variables they will be required in order to connect to the {{ page.product }} droplet.
```

2020-10-20 14:13 UTC, leonatherton commented on _includes/cloud-docker/digitalocean.md
> +3. Submit your username and password
I noticed this section has some differences to the ones already added. Shall we standardise this section across all the articles using an include?

We should also make be consistent with the steps all having a full stop at the end or not

2020-10-21 07:23 UTC, KieranFrance commented on _includes/cloud-docker/digitalocean.md
> +3. Submit your username and password
Agreed, this would make sense. Amy, can you standardize and add as an include (come back to me if you're not sure how) then notify myself and Daniel so we can ensure all articles are using the new include.

2020-10-21 09:39 UTC, daniel-warren commented
@KieranFrance - Regarding using the include, won't it be difficult for us to implement them on our articles until this PR is merged?

@Amy1612 - Feel free to refute, but would it be worth renaming the include to wardownload.md to keep consistent with the naming scheme that _includes seems to use? (e.g. it's dockerclientslink.md not dockerClientsLink.md).

2020-10-28 10:54 UTC, leonatherton approved these changes

2020-10-28 10:55 UTC, merged