Update azure tutorial to detail new docker image approach
idrsolutions/idrsolutions.github.io pull request #6
Opened 2020-10-30 10:17 UTC by KieranFrance

2020-10-30 12:04 UTC, daniel-warren requested changes
@KieranFrance I have taken a first pass at reviewing the changes and have suggested some changes. I plan to take another look on Monday.

2020-10-30 12:04 UTC, daniel-warren commented on _includes/cloud-docker/azure.md
> + You need to select the Virtual machine to use. I suggest using atleast "Standard_B2ms" which can be found by clicking the "Select size" link.
Same suggestion as above:
```suggestion
 You need to select the Virtual machine to use. We suggest using atleast "Standard_B2ms" which can be found by clicking the "Select size" link.
```

2020-10-30 12:04 UTC, daniel-warren commented on _includes/cloud-docker/azure.md
> +Whilst it is not required I would recommend changing the username from the default value
```suggestion
Whilst it is not required we would recommend changing the username from the default value
```

2020-11-02 09:08 UTC, Amy1612 commented on _includes/cloud-docker/azure.md
> + - **Select inbound ports**
Do we need two headings here?

2020-11-02 09:08 UTC, Amy1612 commented on _includes/cloud-docker/azure.md
> +Download this file then you can then click the create button to create the virtual machine.
I think you should remove one of the 'then's here

2020-11-02 12:04 UTC, daniel-warren requested changes
@KieranFrance - Ran through and made suggestions for wording/grammar in order to be more concise (I've always been told to be concise with tutorials/instructions). 
Please do refute any suggestions you think do not make sense.

2020-11-02 12:04 UTC, daniel-warren commented on _includes/cloud-docker/azure.md
> +If you are trialing {{page.product}} or maybe you just don't need your virtual machine for a while you may wish to prevent it from being used or remove it altogether. This is simple to do. If you nav
Grammar:
```suggestion
If you are trialling {{page.product}} or maybe you just don't need your virtual machine for a while, you may wish to prevent it from being used or remove it altogether. This is simple to do. If you navigate to your virtual machine page you will find the following options on the overview page.
```

2020-11-10 14:50 UTC, KieranFrance commented
@daniel-warren @Amy1612 
All suggestions have been implemented.
Due to the site migration, all changes have been implemented in the new repo.
FOr this reason, I am closing this pull request.

2020-11-10 14:50 UTC, closed without merging