Feature/update aws to include war
idrsolutions/idrsolutions.github.io pull request #7
Opened 2020-11-03 11:06 UTC by Amy1612

I wasn't able to properly test the new way of enabling HTTPS, would one of you please be able to or be able to show me how to?

2020-11-03 14:31 UTC, daniel-warren requested changes
@Amy1612 Have noticed a few minor things to amend, otherwise looks promising.

2020-11-03 14:31 UTC, daniel-warren commented on _includes/cloud-docker/aws.md
> +scp -i <path/to/key.pem> path/to/war{{page.product |downcase}}-microservice.war ec2-user@<YourPublicDNS>:~
Missing a /
```suggestion
scp -i <path/to/key.pem> path/to/war/{{page.product | downcase}}-microservice.war ec2-user@<YourPublicDNS>:~
```

2020-11-03 14:31 UTC, daniel-warren commented on _includes/cloud-docker/aws.md
> +docker run -p 80:80 --mount "source=/home/ec2-user/{{page.product | dowcase}}-microservice.war,target=/usr/local/tomcat/webapps/ROOT.war,type=bind" idrsolutions/{{page.product}}
Typo stops it from being changed to lowercase
```suggestion
docker run -p 80:80 --mount "source=/home/ec2-user/{{page.product | downcase}}-microservice.war,target=/usr/local/tomcat/webapps/ROOT.war,type=bind" idrsolutions/{{page.product}}
```

2020-11-03 14:31 UTC, daniel-warren commented on _includes/cloud-docker/aws.md
> +![16](/assets/images/aws/15.png)
Was image 15 meant to be deleted in the commits? It's not loading for me as the file is removed

2020-11-03 14:42 UTC, Amy1612 commented on _includes/cloud-docker/aws.md
> +![16](/assets/images/aws/15.png)
Sorry I didn't add the new image 15, have done so now

2020-11-03 14:47 UTC, daniel-warren approved these changes

2020-11-10 14:37 UTC, KieranFrance approved these changes
Aproved but as we are moving the site I will close this pull request and manually move changes into the new rep

2020-11-10 14:38 UTC, closed without merging